spring.application.name=IncidentInvestigator
incident-analyzer.base-url=http://localhost:8000


spring.datasource.url=jdbc:postgresql://localhost:5432/incidentdb
spring.datasource.username=incident
spring.datasource.password=incidentpass
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver